### ISSUE TITLE
"A SMALL TASTE" button does nothing

### ISSUE THREAD

**Issue by tobeorla** [phalcon/zephir-website#9]
**O.S**: Windows 10
**Browser**: Chrome
**URL**: https://zephir-lang.com/

The  "A SMALL TASTE" "See what zephir can do!" button does nothing. No Javascript errors got thrown.

**Comment by sergeyklay** [comment]
Fixed in the `master` branch.

**Comment by richard-dicristino-arc** [comment]
This still doesn't do anything. From what I see in the last commit, all it does is make it reactive based on language. There seems to still be no logic attached to it.
